### ISSUE TITLE
I got FileNotFoundError ... 

### ISSUE THREAD

**Issue by zzzeddy** [gusdnd852/Chatbot#2]
Hi, 

I got error message during run main.py as follows,

(py6) dweom@soynet:~/prog/Chatbot$ python main.py
...
AI is awakening now...
Provided Feature : 날씨, 뉴스, 달력, 맛집, 미세먼지, 명언, 번역, 시간, 위키, 음악, 이슈, 인물
...
Traceback (most recent call last):
 File "main.py", line 27, in <module>
   main()
 File "main.py", line 8, in main
   import application as app
 File "/nipa/home/dweom/prog/Chatbot/application.py", line 10, in <module>
   from src.intent.classifier import get_intent
 File "/nipa/home/dweom/prog/Chatbot/src/intent/classifier.py", line 13, in <module>
   configs = IntentConfigs()
 File "/nipa/home/dweom/prog/Chatbot/src/intent/configs.py", line 20, in __init__
   self.data = pd.read_csv(self.root_path + 'train_intent.csv')
 File "/home/dweom/.conda/envs/py6/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
   return _read(filepath_or_buffer, kwds)
 File "/home/dweom/.conda/envs/py6/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
   parser = TextFileReader(filepath_or_buffer, **kwds)
 File "/home/dweom/.conda/envs/py6/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
   self._make_engine(self.engine)
 File "/home/dweom/.conda/envs/py6/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
   self._engine = CParserWrapper(self.f, **self.options)
 File "/home/dweom/.conda/envs/py6/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
   self._reader = parsers.TextReader(src, **kwds)
 File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
 File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
**FileNotFoundError: [Errno 2] File b'intent/train_intent.csv' does not exist: b'intent/train_intent.csv'**

My test environment 
 - OS : Ubuntu 18.04 LTS
 - Python : 3.6.7

To run, I did as follows,

~/prog$ git clone https://github.com/gusdnd852/Chatbot
~/prog$ cd Chatbot
~/prog/Chatbot$ cp src/main.py ./
~/prog/Chatbot$ cp src/application.py ./
~/prog/Chatbot$ vi main.py 

def main():
   #import src.application as app
   import application as app

~/prog/Chatbot$ python main.py

**Comment by zzzeddy** [comment]
problem is resolved by doing as follows, (with original files without modifying source)

~prog/Chatbot/src$ cp main.py ../
~prog/Chatbot/src$ python ../main.py

**Comment by zzzeddy** [comment]
problem is resolved by doing as follows, (with original files without modifying source)

~prog/Chatbot/src$ cp main.py ../
~prog/Chatbot/src$ python ../main.py
